export default {
  "login": "kucheriavii",
  "id": 5351305,
  "node_id": "MDQ6VXNlcjUzNTEzMDU=",
  "avatar_url": "https://avatars.githubusercontent.com/u/5351305?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kucheriavii",
  "html_url": "https://github.com/kucheriavii",
  "followers_url": "https://api.github.com/users/kucheriavii/followers",
  "following_url": "https://api.github.com/users/kucheriavii/following{/other_user}",
  "gists_url": "https://api.github.com/users/kucheriavii/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kucheriavii/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kucheriavii/subscriptions",
  "organizations_url": "https://api.github.com/users/kucheriavii/orgs",
  "repos_url": "https://api.github.com/users/kucheriavii/repos",
  "events_url": "https://api.github.com/users/kucheriavii/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kucheriavii/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Roman Ostapchuk",
  "company": "The greatest company",
  "blog": "Nothing about",
  "location": 'Facked Volyn',
  "email": null,
  "hireable": null,
  "bio": "Frontend: Js, React, HTML+CSS\r\n\r\nBack end: nodejs, python, PHP\r\n\r\nDataAnalyst: Anaconda, R, Vba",
  "twitter_username": "kucheriavii_r",
  "public_repos": 62,
  "public_gists": 11,
  "followers": 100,
  "following": 131,
  "created_at": "2013-08-31T05:07:57Z",
  "updated_at": "2023-09-12T18:48:13Z"
};
